CREATE TABLE EmployeeProfile (
    id INT(10),
    employeeINT VARCHAR(10),
    name VARCHAR(50),
    position VARCHAR(30),
    icINT VARCHAR(20),
    passportINT VARCHAR(20),
    gender VARCHAR(3),
    religion VARCHAR(20),
    maritalStatus VARCHAR(10),
    workEmailAddress VARCHAR(50),
    personalEmailAddress VARCHAR(50),
    officePhone VARCHAR(20),
    personalPhone VARCHAR(20),
    nationality VARCHAR(40),
    leaveEntitlement INT(3),
    leaveBalance INT(3),
    username VARCHAR(20),
    employeeGradeId INT(10),
    departmentId INT(10),
    employeeTypeId INT(10),
    correspondanceAddressId INT(10),
    joinDate DATE,
    resignationDate DATE,
    isDeleted CHAR(1),
    isResigned CHAR(1),
    PRIMARY KEY (id)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;